# Generated by Django 4.2.7 on 2025-07-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_workflow_workflowstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'workflow_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStageTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_index', models.PositiveIntegerField()),
                ('stage_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('stage_type', models.CharField(choices=[('screening', 'Screening'), ('interview', 'Interview'), ('assessment', 'Assessment'), ('reference_check', 'Reference Check'), ('offer', 'Offer'), ('onboarding', 'Onboarding'), ('custom', 'Custom')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api.workflowtemplate')),
            ],
            options={
                'db_table': 'workflow_stage_templates',
                'ordering': ['template', 'order_index'],
                'unique_together': {('template', 'order_index')},
            },
        ),
    ]
