# Generated by Django 4.2.7 on 2025-08-03 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_application_application_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="notes",
        ),
    ]
